# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'revview/settings.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_SettingsDialog(object):
    def setupUi(self, SettingsDialog):
        SettingsDialog.setObjectName("SettingsDialog")
        SettingsDialog.resize(310, 280)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(SettingsDialog.sizePolicy().hasHeightForWidth())
        SettingsDialog.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Meiryo UI")
        SettingsDialog.setFont(font)
        self.label = QtWidgets.QLabel(SettingsDialog)
        self.label.setGeometry(QtCore.QRect(30, 20, 161, 21))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(SettingsDialog)
        self.label_2.setGeometry(QtCore.QRect(30, 70, 161, 21))
        self.label_2.setObjectName("label_2")
        self.lineWidthSB = QtWidgets.QSpinBox(SettingsDialog)
        self.lineWidthSB.setGeometry(QtCore.QRect(200, 70, 61, 22))
        self.lineWidthSB.setMinimum(1)
        self.lineWidthSB.setMaximum(10)
        self.lineWidthSB.setObjectName("lineWidthSB")
        self.lineColorBtn = QtWidgets.QPushButton(SettingsDialog)
        self.lineColorBtn.setGeometry(QtCore.QRect(220, 20, 23, 23))
        self.lineColorBtn.setText("")
        self.lineColorBtn.setObjectName("lineColorBtn")
        self.ignoreBgCB = QtWidgets.QCheckBox(SettingsDialog)
        self.ignoreBgCB.setGeometry(QtCore.QRect(30, 120, 251, 21))
        self.ignoreBgCB.setChecked(True)
        self.ignoreBgCB.setObjectName("ignoreBgCB")
        self.label_5 = QtWidgets.QLabel(SettingsDialog)
        self.label_5.setGeometry(QtCore.QRect(50, 160, 81, 21))
        self.label_5.setObjectName("label_5")
        self.bgColorBtn = QtWidgets.QPushButton(SettingsDialog)
        self.bgColorBtn.setGeometry(QtCore.QRect(220, 160, 23, 23))
        self.bgColorBtn.setText("")
        self.bgColorBtn.setObjectName("bgColorBtn")
        self.applyMDesignCB = QtWidgets.QCheckBox(SettingsDialog)
        self.applyMDesignCB.setGeometry(QtCore.QRect(30, 200, 251, 21))
        self.applyMDesignCB.setChecked(True)
        self.applyMDesignCB.setObjectName("applyMDesignCB")
        self.label_3 = QtWidgets.QLabel(SettingsDialog)
        self.label_3.setGeometry(QtCore.QRect(50, 220, 231, 21))
        font = QtGui.QFont()
        font.setFamily("Meiryo UI")
        font.setPointSize(8)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")

        self.retranslateUi(SettingsDialog)
        QtCore.QMetaObject.connectSlotsByName(SettingsDialog)

    def retranslateUi(self, SettingsDialog):
        _translate = QtCore.QCoreApplication.translate
        SettingsDialog.setWindowTitle(_translate("SettingsDialog", "設定"))
        self.label.setText(_translate("SettingsDialog", "枠線の色："))
        self.label_2.setText(_translate("SettingsDialog", "枠線の太さ (pix)："))
        self.ignoreBgCB.setText(_translate("SettingsDialog", "背景色の検出領域を無視する"))
        self.label_5.setText(_translate("SettingsDialog", "背景色："))
        self.applyMDesignCB.setText(_translate("SettingsDialog", "レガシーデザインを適用する"))
        self.label_3.setText(_translate("SettingsDialog", "※再起動後に反映されます"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    SettingsDialog = QtWidgets.QDialog()
    ui = Ui_SettingsDialog()
    ui.setupUi(SettingsDialog)
    SettingsDialog.show()
    sys.exit(app.exec_())
